i9567: Made resource a function parameter instead of undefined val
sbt:i9567> compile
[info] Compiling 1 Scala source to /src/i9567/target/scala-0.26/classes ...
[error] -- [E008] Not Found Error: /src/i9567/src/main/scala/Main.scala:4:10 -----------
[error] 4 |    res <-resource.allocated
[error]   |          ^^^^^^^^^^^^^^^^^^
[error]   |    value map is not a member of List[Unit] - did you mean List[Unit].map?
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Sep 17, 2020, 3:35:33 PM