i9567: Swap in scala List for the "effect" instead of IO
sbt:i9567> compile
[info] Compiling 1 Scala source to /src/i9567/target/scala-0.26/classes ...
[error] -- [E008] Not Found Error: /src/i9567/src/main/scala/Main.scala:8:11 -----------
[error] 8 |    res <- resource.allocated
[error]   |           ^^^^^^^^^^^^^^^^^^
[error]   |value map is not a member of List[(Unit, List[Unit])], but could be made available as an extension method.
[error]   |
[error]   |One of the following imports might fix the problem:
[error]   |
[error]   |  import cats.Alternative.ops.toAllAlternativeOps
[error]   |  import cats.Applicative.ops.toAllApplicativeOps
[error]   |  import cats.Apply.ops.toAllApplyOps
[error]   |  import cats.CoflatMap.ops.toAllCoflatMapOps
[error]   |  import cats.FlatMap.ops.toAllFlatMapOps
[error]   |  import cats.Functor.nonInheritedOps.toFunctorOps
[error]   |  import cats.Functor.ops.toAllFunctorOps
[error]   |  import cats.Monad.ops.toAllMonadOps
[error]   |  import cats.Traverse.ops.toAllTraverseOps
[error]   |  import cats.implicits.toFunctorOps
[error]   |
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed Sep 17, 2020, 12:46:35 PM